### ISSUE TITLE
Review MSS figures to use and include them in quarto 

### ISSUE THREAD

**Issue by sortega87** [orcestra-campaign/weather#55]
Currently the briefing expects the following figures to be added manually. Yet, these are not rendered in the presentation:

```
  mss_side_view:
    ICON:
      cloud_cover: fig/mss/MSS_FLX1_sideview_ICON_20240726T0000Z_cloud_cover.png
      relative_humidity: fig/mss/MSS_FLX1_sideview_ICON_20240726T0000Z_relative_humidity.png
    IFS:
      cloud_cover: fig/mss/MSS_FLX1_sideview_IFS_20240726T0000Z_cloud_cover.png
      relative_humidity: fig/mss/MSS_FLX1_sideview_IFS_20240726T0000Z_relative_humidity.png
```

To resolve the issue we then need to:
- Define MSS figures in get_expected_mss_side_view_figures (if needed).
https://github.com/orcestra-campaign/weather/blob/6336a8c6c2de3d9ea240477ebdb022418063b16e/src/wblib/services/get_expected_figures_yaml.py#L55
- Include the figures with new slides in "src/wblib/template.qmd"
